# Tomcat
server:
    tomcat:
        max-threads: 10
        min-spare-threads: 10
    port: 80

# mysql
spring:
    profiles:
        active: dev
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        druid:
          first: #数据源1
            url: jdbc:mysql://localhost:3306/report_console?useUnicode=true&characterEncoding=UTF-8
            username: root
            password: root
          second: #数据源2
            url: jdbc:mysql://192.168.0.202:3339/runner_1212?useUnicode=true&characterEncoding=UTF-8
            username: ycc
            password: ycc
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    resources:
            static-locations: classpath:/static/,classpath:/views/

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml

